# Generated by Django 5.1.7 on 2025-03-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('B', 'Bin'), ('AR', 'Archive')], verbose_name='Статус товара'),
        ),
    ]
