# Generated by Django 5.1.7 on 2025-04-01 01:29

import minio_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=minio_storage.storage.MinioMediaStorage, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('A', 'Активный'), ('B', 'В корзине'), ('AR', 'Архивный')], verbose_name='Статус товара'),
        ),
    ]
