# Generated by Django 5.2.1 on 2025-05-10 17:18

import minio_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=minio_storage.storage.MinioMediaStorage(), upload_to='', verbose_name='Картинка'),
        ),
    ]
