# Generated by Django 5.2.1 on 2025-05-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_created_at_cart_finished_at_cart_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='formed_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Сформировано'),
        ),
    ]
