services:
  web:
    build:
      context: ../.
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    env_file:
      - ../.env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - minio
      - redis
    networks:
      - main_net

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main_net

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    networks:
      - main_net

  minio:
    image: minio/minio
    ports:
      - "9002:9002"
      - "9001:9001"
    volumes:
      - minio-data:/data
    env_file:
      - ../.env
    command: server --address 0.0.0.0:9002 --console-address 0.0.0.0:9001 /data
    networks:
      - main_net

volumes:
  postgres-data:
  minio-data:


networks:
  main_net:
    driver: bridge
