services:
  web:
    build: ../backend/.
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db
      - minio
    networks:
      - main_net

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main_net


  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

volumes:
  postgres-data:
  minio-data:

networks:
  main_net:
    driver: bridge
